format = """

╮$custom\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status
│$username\
$hostname\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$lua\
$jobs\
$battery\
$time\
$shell\
$line_break\
└$character"""


[aws]
disabled = true

[[battery.display]]
threshold = 60

# Custom shlvl script to make value zero-indexed.
[custom.shlvl]
# We subtract 2 instead of 1 because this command is run in a subshell of the current shell.
command = "echo $((SHLVL - 2))"
when = """ test "$SHLVL" -gt 2 """
format = "[$output]($style) "
style = "cyan"

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
disabled = true

[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(‹$virtualenv› )]($style)'
symbol = " "
version_format = "${major}.${minor}"

[ruby]
format = "[$symbol($version )]($style)"
version_format = "${raw}"
symbol = " "

[status]
disabled = false
