# PATH
if [[ "$SHLVL" == "1" ]]; then
    # Python (pip install --user)
    PATH="$HOME/.local/bin:$PATH"

    # Ruby
    eval "$(rbenv init -)"

    # Rust
    PATH="$HOME/.cargo/bin:$PATH"

    # Heroku
    PATH="/usr/local/heroku/bin:$PATH"

    # Go
    PATH="$PATH:$GOPATH/bin"

    # Haskell
    PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

    # Git-toolbelt
    PATH="$HOME/personal/dotfiles/git-toolbelt:$PATH"
fi

export EDITOR="nvim"
export MANPAGER="most"
export DELTA_PAGER="cat"


# Pew (replaces virtualenvwrapper)
export WORKON_HOME=~/venvs

# Go
export GOPATH=~/code/go

# Python (avoid pyc files)
export PYTHONDONTWRITEBYTECODE=1

# Docker (and docker-compose)
# Use new build system:
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

# Silver searcher
export AG_COMMAND='ag --hidden --ignore-dir=".git" --ignore-dir=".mypy_cache" --ignore-dir=".tox" --ignore-dir="node_modules"'

eval "$(fnm env)"

export RIPGREP_CONFIG_PATH="$HOME/.ripgrep"
