
export EDITOR="nvim"
export MANPAGER="most"
export DELTA_PAGER="cat"


# Pew (replaces virtualenvwrapper)
export WORKON_HOME=~/venvs

# Go
export GOPATH=~/code/go

# Python (avoid pyc files)
export PYTHONDONTWRITEBYTECODE=1

# Docker (and docker-compose)
# Use new build system:
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

# Silver searcher
export AG_COMMAND='ag --hidden --ignore-dir=".git" --ignore-dir=".mypy_cache" --ignore-dir=".tox" --ignore-dir="node_modules"'

eval "$(fnm env)"
