source ~/.aliases.zsh
source ~/.completion.zsh
source ~/.keybindings.zsh
source ~/.history.zsh
eval "$(starship init zsh)"
#
# PYENV
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

source ~/.sh_rc
