#!/bin/sh
# Rebuilds ctags definitions.
# Called in lots of git hooks.
# Completely stolen from George.
# https://github.com/ghickman/dotfiles/blob/5f8bcda/git_template/hooks/ctags
set -e

trap "rm -f .git/tags.$$" EXIT
dir="`git rev-parse --git-dir`"

git ls-files | \
    /usr/bin/ctags \
    --tag-relative \
    -L - \
    -f.git/tags.$$ \
    --language-force=python \
    --python-kinds=-ivm \
    --exclude={.tox}

mv "$dir"/tags{.$$,}

